// SPDX-FileCopyrightText: 2026 TeamBlackBox Private Limited
// SPDX-License-Identifier: Apache-2.0

import { GIF_FRAME_DELAY_DEFAULT_MS, GIF_FRAME_DELAY_MAX_MS, GIF_FRAME_DELAY_MIN_MS, IMAGE_UPSCALE_SCALES, PHOTO_EDITOR_ADJUSTMENTS, PHOTO_EDITOR_TEXT_COLORS } from "./lib/file-limits.js";
import { BACKGROUND_REMOVAL_BACKGROUNDS, BACKGROUND_REMOVAL_PROFILES } from "./lib/background-removal.js";
import { IMAGE_WATERMARK_ANGLES, IMAGE_WATERMARK_COLORS, IMAGE_WATERMARK_OPACITY_MAX, IMAGE_WATERMARK_OPACITY_MIN, IMAGE_WATERMARK_POSITIONS } from "./lib/image-watermark.js";

const withPhosphorExports = (entries) =>
  Object.freeze(
    entries.map((entry) =>
      Object.freeze({ ...entry, icon: `${entry.icon}Icon` }),
    ),
  );

export const categories = withPhosphorExports([
  {
    id: "organize",
    label: "Organize",
    description: "Arrange, combine, separate, and capture document pages.",
    icon: "Stack",
    accent: "coral",
    order: 10,
  },
  {
    id: "optimize",
    label: "Optimize",
    description: "Reduce file size, restore files, and improve readability.",
    icon: "Gauge",
    accent: "emerald",
    order: 20,
  },
  {
    id: "convert",
    label: "Convert",
    description: "Move between document, image, web, and archive formats.",
    icon: "ArrowsLeftRight",
    accent: "amber",
    order: 30,
  },
  {
    id: "edit",
    label: "Edit",
    description: "Change pages, layouts, text, and image presentation.",
    icon: "PencilSimple",
    accent: "violet",
    order: 40,
  },
  {
    id: "create",
    label: "Create",
    description: "Build expressive images from photos, layouts, and captions.",
    icon: "Sparkle",
    accent: "pink",
    order: 50,
  },
  {
    id: "security",
    label: "Protect",
    description: "Secure, sign, compare, or conceal sensitive content.",
    icon: "ShieldCheck",
    accent: "teal",
    order: 60,
  },
  {
    id: "intelligence",
    label: "Smart",
    description: "Use on-device analysis to understand and transform content.",
    icon: "Brain",
    accent: "indigo",
    order: 70,
  },
]);

export const tools = withPhosphorExports([
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine PDFs and arrange them in the order you need.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: true,
    tags: ["combine", "join", "pages", "documents"],
    icon: "Files",
    featured: true,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Divide one PDF into the page groups you need.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf", ".zip"],
    batch: false,
    tags: ["separate", "extract", "ranges", "pages"],
    icon: "Scissors",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "mode",
        type: "choice",
        label: "Split method",
        default: "half",
        options: [
          { value: "half", label: "Split in half", hint: "Create two balanced PDFs." },
          { value: "every2", label: "Every 2 pages", hint: "Create consecutive two-page PDFs." },
          { value: "odd", label: "Odd pages", hint: "Group all odd pages in one PDF." },
          { value: "even", label: "Even pages", hint: "Group all even pages in one PDF." },
          { value: "custom", label: "Custom", hint: "Choose exactly where each PDF ends." },
        ],
      },
      {
        key: "customBreaks",
        type: "text",
        label: "Split after pages",
        default: "",
        hint: "Example: 3, 6 creates pages 1–3, 4–6, and 7 onward.",
      },
    ],
  },
  {
    slug: "remove-pdf-pages",
    name: "Remove Pages",
    description: "Delete selected pages while preserving the rest of the PDF.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["delete", "pages", "trim", "document"],
    icon: "FileMinus",
    featured: false,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "extract-pdf-pages",
    name: "Extract Pages",
    description: "Save selected PDF pages as one file or separate files.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf", ".zip"],
    batch: false,
    tags: ["copy", "select", "pages", "separate"],
    icon: "FileArrowUp",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "combine",
        type: "toggle",
        label: "Combine extracted pages",
        default: true,
      },
    ],
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    description: "Reorder, duplicate, or omit pages with an explicit page order.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["reorder", "sort", "duplicate", "pages"],
    icon: "Stack",
    featured: true,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Assemble uploaded camera images into an ordered PDF.",
    kind: "pdf",
    category: "organize",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".pdf"],
    batch: true,
    tags: ["camera", "capture", "document", "mobile"],
    icon: "Scan",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "pageSize",
        type: "select",
        label: "Page size",
        default: "auto",
        options: [
          { value: "auto", label: "Match image", hint: "Keep each scan's natural shape." },
          { value: "a4", label: "A4", hint: "Standard international paper." },
          { value: "letter", label: "US Letter", hint: "Standard North American paper." },
        ],
      },
    ],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Shrink a PDF while balancing clarity and file size.",
    kind: "pdf",
    category: "optimize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["reduce", "shrink", "size", "quality"],
    icon: "FileZip",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "quality",
        type: "select",
        label: "Compression",
        default: "balanced",
        options: [
          { value: "gentle", label: "Gentle", badge: "Best clarity", hint: "Light reduction", description: "Keeps page images sharper and produces a larger result." },
          { value: "balanced", label: "Balanced", badge: "Recommended", hint: "Medium reduction", description: "A practical clarity and file-size trade-off for sharing." },
          { value: "strong", label: "Strong", badge: "Smallest target", hint: "Most reduction", description: "Uses lower image resolution; fine text may look softer." },
        ],
      },
    ],
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Rebuild recoverable PDF structure into a fresh local copy.",
    kind: "pdf",
    category: "optimize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["fix", "recover", "corrupt", "restore"],
    icon: "Wrench",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "ocr-pdf",
    name: "OCR Reader",
    description: "Read and copy text from scanned English PDFs with on-device recognition.",
    kind: "pdf",
    category: "optimize",
    accepts: [".pdf"],
    output: ["text reader"],
    batch: false,
    tags: ["reader", "copy", "scan", "recognize", "text"],
    icon: "TextT",
    featured: true,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Turn JPG and PNG images into an ordered PDF.",
    kind: "pdf",
    category: "convert",
    accepts: [".jpg", ".jpeg", ".png"],
    output: [".pdf"],
    batch: true,
    tags: ["image", "photo", "convert", "combine"],
    icon: "FilePdf",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "pageSize",
        type: "select",
        label: "Page size",
        default: "fit",
        options: [
          { value: "fit", label: "Fit each image", hint: "Every page follows its image." },
          { value: "a4", label: "A4", hint: "Use one consistent A4 page size." },
          { value: "letter", label: "US Letter", hint: "Use one consistent Letter page size." },
        ],
      },
      {
        key: "margin",
        type: "select",
        label: "Margin",
        default: "small",
        options: [
          { value: "none", label: "None", hint: "Fill the available page area." },
          { value: "small", label: "Small", hint: "A neat edge around each image." },
          { value: "large", label: "Large", hint: "More white space around the image." },
        ],
      },
    ],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Extract readable DOCX text into a clean PDF without preserving the original layout.",
    kind: "pdf",
    category: "convert",
    accepts: [".docx"],
    output: [".pdf"],
    batch: false,
    tags: ["word", "docx", "text", "office"],
    icon: "FileDoc",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    description: "Extract PPTX slide text into a clean PDF without preserving slide layout.",
    kind: "pdf",
    category: "convert",
    accepts: [".pptx"],
    output: [".pdf"],
    batch: false,
    tags: ["powerpoint", "pptx", "text", "slides"],
    icon: "FilePpt",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Lay out spreadsheet cell text in a readable PDF without preserving workbook styling.",
    kind: "pdf",
    category: "convert",
    accepts: [".xls", ".xlsx"],
    output: [".pdf"],
    batch: false,
    tags: ["excel", "xls", "xlsx", "spreadsheet"],
    icon: "FileXls",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "orientation",
        type: "select",
        label: "Page orientation",
        default: "landscape",
        options: [
          { value: "portrait", label: "Portrait", hint: "Taller pages for narrow tables." },
          { value: "landscape", label: "Landscape", hint: "Wider pages for more columns." },
        ],
      },
    ],
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Extract readable text from local HTML into a clean, self-contained PDF.",
    kind: "pdf",
    category: "convert",
    accepts: [".html", ".htm"],
    output: [".pdf"],
    batch: false,
    tags: ["html", "webpage", "text", "document"],
    icon: "FileHtml",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "pageSize",
        type: "select",
        label: "Page size",
        default: "a4",
        options: [
          { value: "a4", label: "A4", hint: "Standard international paper." },
          { value: "letter", label: "US Letter", hint: "Standard North American paper." },
        ],
      },
    ],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Render every PDF page as a JPG image.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".jpg", ".zip"],
    batch: false,
    tags: ["image", "photo", "pages", "extract"],
    icon: "FileJpg",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "quality",
        type: "range",
        label: "JPG quality",
        default: 88,
        min: 40,
        max: 100,
        step: 1,
        suffix: "%",
        minLabel: "Smaller files",
        maxLabel: "Sharper pages",
      },
    ],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Reconstruct selectable PDF text as an editable DOCX, one section per page.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".docx"],
    batch: false,
    tags: ["word", "docx", "editable", "office"],
    icon: "FileDoc",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Place selectable text from each PDF page onto a simple editable slide.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".pptx"],
    batch: false,
    tags: ["powerpoint", "pptx", "slides", "presentation"],
    icon: "FilePpt",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Place selectable text from each PDF page into a separate workbook sheet.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".xlsx"],
    batch: false,
    tags: ["excel", "xlsx", "pages", "spreadsheet"],
    icon: "FileXls",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-to-pdfa",
    name: "Archive PDF Rewrite",
    description: "Rewrite a PDF into an archive-friendly file; formal PDF/A conformance is not certified.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["archive", "rewrite", "preserve", "normalize"],
    icon: "Archive",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate every page in a PDF by the selected angle.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["turn", "orientation", "pages", "landscape"],
    icon: "ArrowClockwise",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "angle",
        type: "select",
        label: "Rotation",
        default: 90,
        options: [
          { value: 90, label: "90° clockwise", hint: "Turn right." },
          { value: 180, label: "180°", hint: "Turn upside down." },
          { value: 270, label: "90° counter-clockwise", hint: "Turn left." },
        ],
      },
    ],
  },
  {
    slug: "add-pdf-page-numbers",
    name: "Add Page Numbers",
    description: "Place sequential page numbers with a chosen position and starting number.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["number", "footer", "header", "pagination"],
    icon: "ListNumbers",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "position",
        type: "select",
        label: "Position",
        default: "bottom-center",
        compactChoices: true,
        choiceColumns: 3,
        options: [
          { value: "top-left", label: "Top left" },
          { value: "top-center", label: "Top center" },
          { value: "top-right", label: "Top right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
      {
        key: "startAt",
        type: "number",
        label: "Start at",
        default: 1,
        min: 1,
        step: 1,
        hint: "The first output page displays this number.",
      },
    ],
  },
  {
    slug: "watermark-pdf",
    name: "Add Watermark",
    description: "Stamp centered diagonal text across every PDF page.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["stamp", "text", "brand", "overlay"],
    icon: "Stamp",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "text",
        type: "text",
        label: "Watermark text",
        default: "CONFIDENTIAL",
      },
      {
        key: "opacity",
        type: "range",
        label: "Opacity",
        default: 25,
        min: 5,
        max: 100,
        step: 5,
        suffix: "%",
        minLabel: "Subtle",
        maxLabel: "Solid",
      },
    ],
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Trim the same percentage from every edge on every PDF page.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["trim", "margins", "area", "pages"],
    icon: "Crop",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "margin",
        type: "range",
        label: "Trim each edge",
        default: 5,
        min: 0,
        max: 42,
        step: 1,
        suffix: "%",
        minLabel: "Keep more",
        maxLabel: "Crop more",
      },
    ],
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Place a text annotation at the same position on every PDF page.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["annotate", "text", "label", "pages"],
    icon: "PencilSimple",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "text",
        type: "text",
        label: "Text to add",
        default: "Reviewed locally",
      },
      {
        key: "position",
        type: "select",
        label: "Position",
        default: "top-left",
        compactChoices: true,
        options: [
          { value: "top-left", label: "Top left" },
          { value: "top-right", label: "Top right" },
          { value: "center", label: "Center" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
      {
        key: "fontSize",
        type: "range",
        label: "Text size",
        default: 16,
        min: 10,
        max: 48,
        step: 1,
        suffix: "px",
        minLabel: "Small",
        maxLabel: "Large",
      },
    ],
  },
  {
    slug: "add-image-to-pdf",
    name: "Add Image to PDF",
    description: "Place signatures or images anywhere on PDF pages with visual resize and rotation controls.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["signature", "image", "stamp", "overlay", "paste", "place"],
    icon: "ImageSquare",
    featured: true,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-forms",
    name: "PDF Forms",
    description: "See and fill existing interactive PDF fields with familiar controls.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["form", "fields", "checkbox", "fillable"],
    icon: "Textbox",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "values",
        type: "textarea",
        label: "Advanced field JSON",
        default: "",
        hidden: true,
      },
      {
        key: "flatten",
        type: "toggle",
        label: "Flatten fields on export",
        default: false,
      },
    ],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove a PDF password when you are authorized to do so.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["password", "decrypt", "access", "open"],
    icon: "LockOpen",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "password",
        type: "password",
        label: "Current password",
        default: "",
        required: true,
      },
    ],
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Encrypt a PDF locally with an AES-256 password before sharing it.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["password", "encrypt", "secure", "privacy"],
    icon: "Lock",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "password",
        type: "password",
        label: "New password",
        default: "",
        required: true,
      },
    ],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Place a typed signature and optional date on the final PDF page.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["signature", "approve", "initial", "document"],
    icon: "Signature",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "name",
        type: "text",
        label: "Typed signature",
        default: "Signed locally",
        hint: "Added to the final page above a signature line.",
      },
      {
        key: "includeDate",
        type: "toggle",
        label: "Include signing date",
        default: true,
      },
    ],
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Draw permanent redaction areas on the exact PDF pages that need them.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["hide", "remove", "sensitive", "privacy"],
    icon: "EyeSlash",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "overlay",
        type: "select",
        label: "Redaction style",
        default: "black",
        options: [
          { value: "black", label: "Black box", hint: "Clear, conventional redaction." },
          { value: "white", label: "White space", hint: "Blend the removed area into the page." },
        ],
      },
      {
        key: "regions",
        type: "hidden",
        label: "Redaction areas",
        default: "[]",
      },
    ],
  },
  {
    slug: "compare-pdf",
    name: "Compare PDF",
    description: "Review selectable-text changes inline and optionally save a local HTML report.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".html"],
    batch: false,
    tags: ["difference", "versions", "review", "changes"],
    icon: "Columns",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "summarize-pdf",
    name: "Local Summarizer",
    description: "Create an extractive summary from selectable PDF text entirely on your device.",
    kind: "pdf",
    category: "intelligence",
    accepts: [".pdf"],
    output: ["text reader", ".txt"],
    batch: false,
    tags: ["summary", "extractive", "notes", "key points"],
    icon: "Sparkle",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "length",
        type: "select",
        label: "Summary length",
        default: "medium",
        options: [
          { value: "short", label: "Brief", hint: "Only the central takeaways." },
          { value: "medium", label: "Standard", hint: "A balanced summary." },
          { value: "long", label: "Detailed", hint: "More supporting context." },
        ],
      },
      {
        key: "format",
        type: "select",
        label: "Format",
        default: "bullets",
        options: [
          { value: "bullets", label: "Key points", hint: "Fast to scan and copy." },
          { value: "prose", label: "Paragraphs", hint: "Read as a continuous summary." },
        ],
      },
    ],
  },
  {
    slug: "translate-pdf",
    name: "Translate PDF",
    description: "Translate selectable English PDF text with an on-device model or a limited offline glossary.",
    kind: "pdf",
    category: "intelligence",
    accepts: [".pdf"],
    output: ["text reader", ".txt"],
    batch: false,
    tags: ["language", "translate", "localize", "offline"],
    icon: "Translate",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "targetLanguage",
        type: "select",
        label: "Translate to",
        default: "es",
        compactChoices: true,
        options: [
          { value: "hi", label: "Hindi" },
          { value: "es", label: "Spanish" },
          { value: "de", label: "German" },
          { value: "fr", label: "French" },
        ],
      },
    ],
  },
  {
    slug: "pdf-to-markdown",
    name: "PDF to Markdown",
    description: "Convert selectable PDF text into an editable Markdown draft.",
    kind: "pdf",
    category: "intelligence",
    accepts: [".pdf"],
    output: ["Markdown reader", ".md"],
    batch: false,
    tags: ["markdown", "md", "text", "llm"],
    icon: "MarkdownLogo",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "pageBreaks",
        type: "toggle",
        label: "Mark page breaks",
        default: false,
      },
    ],
  },
  {
    slug: "compress-image",
    name: "Compress Image",
    description: "Re-encode JPG, PNG, or WebP images locally and remove metadata.",
    kind: "image",
    category: "optimize",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["reduce", "shrink", "quality", "optimize"],
    icon: "Images",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "quality",
        type: "range",
        label: "Quality",
        default: 82,
        min: 20,
        max: 100,
        step: 1,
        suffix: "%",
        minLabel: "Smaller file",
        maxLabel: "Sharper image",
      },
    ],
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    description: "Resize image batches to a target width without distortion.",
    kind: "image",
    category: "edit",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["dimensions", "pixels", "percent", "scale"],
    icon: "Resize",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "width",
        type: "number",
        label: "Width",
        default: 1920,
        min: 1,
        step: 10,
        suffix: "px",
        hint: "Height adjusts automatically to preserve proportions.",
        presets: [
          { value: 640, label: "Small" },
          { value: 1280, label: "Web" },
          { value: 1920, label: "Full HD" },
          { value: 2560, label: "Large" },
        ],
      },
    ],
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    description: "Crop photos freely or with a consistent aspect ratio.",
    kind: "image",
    category: "edit",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["trim", "aspect", "rectangle", "frame"],
    icon: "Crop",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "aspectRatio",
        type: "select",
        label: "Aspect ratio",
        default: "free",
        options: [
          { value: "free", label: "Original", hint: "Keep the image’s shape." },
          { value: "1:1", label: "Square · 1:1", hint: "Profiles and social posts." },
          { value: "4:3", label: "Standard · 4:3", hint: "Classic photo shape." },
          { value: "16:9", label: "Wide · 16:9", hint: "Screens and video covers." },
        ],
      },
      {
        key: "cropScale",
        type: "range",
        label: "Crop size",
        default: 100,
        min: 40,
        max: 100,
        step: 1,
        suffix: "%",
        hint: "Lower values create a tighter crop.",
      },
      { key: "focusX", type: "number", label: "Horizontal crop position", default: 50, min: 0, max: 100, step: 1, suffix: "%" },
      { key: "focusY", type: "number", label: "Vertical crop position", default: 50, min: 0, max: 100, step: 1, suffix: "%" },
    ],
  },
  {
    slug: "convert-image",
    name: "Convert Image",
    description: "Convert common images to PNG, JPG, or WebP without uploading them.",
    kind: "image",
    category: "convert",
    accepts: [
      ".jpg",
      ".jpeg",
      ".png",
      ".gif",
      ".tif",
      ".tiff",
      ".svg",
      ".webp",
    ],
    output: [".png", ".jpg", ".webp"],
    batch: true,
    tags: ["png", "jpeg", "jpg", "webp", "format", "transparency"],
    icon: "ArrowsLeftRight",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "format",
        type: "select",
        label: "Output format",
        default: "webp",
        options: [
          { value: "webp", label: "WebP" },
          { value: "png", label: "PNG" },
          { value: "jpg", label: "JPG" },
        ],
      },
      {
        key: "quality",
        type: "range",
        label: "Lossy quality",
        default: 88,
        min: 40,
        max: 100,
        step: 1,
        suffix: "%",
      },
      {
        key: "background",
        type: "color",
        label: "JPG transparency fill",
        default: "#ffffff",
      },
    ],
  },
  {
    slug: "convert-from-jpg",
    name: "JPG to GIF",
    description: "Combine JPG images into one animated GIF in your chosen order.",
    kind: "image",
    category: "convert",
    accepts: [".jpg", ".jpeg"],
    output: [".gif"],
    batch: true,
    tags: ["gif", "animation", "frames", "slideshow"],
    icon: "ArrowsLeftRight",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "delay",
        type: "range",
        label: "Time per image",
        default: GIF_FRAME_DELAY_DEFAULT_MS,
        min: GIF_FRAME_DELAY_MIN_MS,
        max: GIF_FRAME_DELAY_MAX_MS,
        step: 100,
        suffix: "ms",
        minLabel: "Faster",
        maxLabel: "Slower",
      },
      {
        key: "loop",
        type: "toggle",
        label: "Loop continuously",
        default: true,
        hint: "Restart the animation after the final image.",
      },
    ],
  },
  {
    slug: "photo-editor",
    name: "Photo Editor",
    description: "Adjust brightness, contrast, and saturation or add a text caption.",
    kind: "image",
    category: "create",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: false,
    tags: ["effects", "text", "brightness", "contrast"],
    icon: "Palette",
    featured: true,
    maturity: "beta",
    settings: [
      { key: "brightness", type: "range", label: "Brightness", default: PHOTO_EDITOR_ADJUSTMENTS.brightness.default, min: PHOTO_EDITOR_ADJUSTMENTS.brightness.min, max: PHOTO_EDITOR_ADJUSTMENTS.brightness.max, step: 5, suffix: "%", minLabel: "Darker", maxLabel: "Brighter" },
      { key: "contrast", type: "range", label: "Contrast", default: PHOTO_EDITOR_ADJUSTMENTS.contrast.default, min: PHOTO_EDITOR_ADJUSTMENTS.contrast.min, max: PHOTO_EDITOR_ADJUSTMENTS.contrast.max, step: 5, suffix: "%", minLabel: "Softer", maxLabel: "Stronger" },
      { key: "saturation", type: "range", label: "Color", default: PHOTO_EDITOR_ADJUSTMENTS.saturation.default, min: PHOTO_EDITOR_ADJUSTMENTS.saturation.min, max: PHOTO_EDITOR_ADJUSTMENTS.saturation.max, step: 5, suffix: "%", minLabel: "Muted", maxLabel: "Vivid" },
      { key: "warmth", type: "range", label: "Warmth", default: PHOTO_EDITOR_ADJUSTMENTS.warmth.default, min: PHOTO_EDITOR_ADJUSTMENTS.warmth.min, max: PHOTO_EDITOR_ADJUSTMENTS.warmth.max, step: 5, suffix: "%", minLabel: "Neutral", maxLabel: "Warm" },
      { key: "text", type: "text", label: "Optional caption", default: "", hint: "Leave blank to export only the image adjustments." },
      {
        key: "textColor",
        type: "select",
        label: "Caption color",
        default: PHOTO_EDITOR_TEXT_COLORS[0],
        options: [
          { value: PHOTO_EDITOR_TEXT_COLORS[0], label: "Light", hint: "White text with a dark shadow." },
          { value: PHOTO_EDITOR_TEXT_COLORS[1], label: "Dark", hint: "Ink text with a light shadow." },
        ],
      },
    ],
  },
  {
    slug: "upscale-image",
    name: "Upscale Image",
    description: "Enlarge an image with high-quality on-device resampling.",
    kind: "image",
    category: "optimize",
    accepts: [".jpg", ".jpeg", ".png"],
    output: [".jpg", ".png"],
    batch: true,
    tags: ["enlarge", "resolution", "resample", "scale"],
    icon: "ArrowsOut",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "scale",
        type: "select",
        label: "Scale",
        default: IMAGE_UPSCALE_SCALES[0],
        options: [
          { value: IMAGE_UPSCALE_SCALES[0], label: "2×", hint: "A practical size increase." },
          { value: IMAGE_UPSCALE_SCALES[1], label: "4×", hint: "Much larger and slower." },
        ],
      },
    ],
  },
  {
    slug: "remove-image-background",
    name: "Remove Background",
    description: "Remove simple, flat-color backgrounds with edge-aware local processing.",
    kind: "image",
    category: "optimize",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".png"],
    batch: true,
    tags: ["cutout", "transparent", "flat color", "background"],
    icon: "SelectionBackground",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "cleanup",
        type: "select",
        label: "Background cleanup",
        default: "balanced",
        options: BACKGROUND_REMOVAL_PROFILES.map(({ value, label, hint }) => ({ value, label, hint })),
      },
      {
        key: "background",
        type: "select",
        label: "Background",
        default: "transparent",
        options: BACKGROUND_REMOVAL_BACKGROUNDS.map(({ value, label, hint }) => ({ value, label, hint })),
      },
    ],
  },
  {
    slug: "watermark-image",
    name: "Watermark Image",
    description: "Apply a consistent text watermark across image batches.",
    kind: "image",
    category: "security",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["stamp", "brand", "copyright", "overlay"],
    icon: "Stamp",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "text",
        type: "text",
        label: "Watermark text",
        default: "© My work",
      },
      {
        key: "position",
        type: "select",
        label: "Position",
        default: "bottom-right",
        compactChoices: true,
        choiceColumns: 3,
        options: IMAGE_WATERMARK_POSITIONS.map(({ value, label, hint }) => ({ value, label, hint })),
      },
      {
        key: "angle",
        type: "select",
        label: "Direction",
        default: IMAGE_WATERMARK_ANGLES[0].value,
        options: IMAGE_WATERMARK_ANGLES.map(({ value, label, hint }) => ({ value, label, hint })),
      },
      {
        key: "color",
        type: "select",
        label: "Text color",
        default: IMAGE_WATERMARK_COLORS[0].value,
        options: IMAGE_WATERMARK_COLORS.map(({ value, label, hint }) => ({ value, label, hint })),
      },
      {
        key: "opacity",
        type: "range",
        label: "Opacity",
        default: 45,
        min: IMAGE_WATERMARK_OPACITY_MIN,
        max: IMAGE_WATERMARK_OPACITY_MAX,
        step: 5,
        suffix: "%",
        minLabel: "Subtle",
        maxLabel: "Solid",
      },
    ],
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Overlay high-contrast top and bottom captions on an image.",
    kind: "image",
    category: "create",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: false,
    tags: ["caption", "text", "template", "social"],
    icon: "Smiley",
    featured: false,
    maturity: "ready",
    settings: [
      { key: "topText", type: "text", label: "Top caption", default: "WHEN THE FILE" },
      { key: "bottomText", type: "text", label: "Bottom caption", default: "STAYS ON YOUR DEVICE" },
    ],
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    description: "Rotate image batches by a consistent angle.",
    kind: "image",
    category: "edit",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["turn", "orientation", "landscape", "portrait"],
    icon: "ArrowClockwise",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "angle",
        type: "select",
        label: "Rotation",
        default: 90,
        options: [
          { value: 90, label: "90° clockwise", hint: "Turn right." },
          { value: 180, label: "180°", hint: "Turn upside down." },
          { value: 270, label: "90° counter-clockwise", hint: "Turn left." },
        ],
      },
    ],
  },
  {
    slug: "html-to-image",
    name: "HTML to Image",
    description: "Render sanitized local HTML as a JPG or SVG without loading external assets.",
    kind: "image",
    category: "convert",
    accepts: [".html", ".htm"],
    output: [".jpg", ".svg"],
    batch: false,
    tags: ["html", "webpage", "screenshot", "svg"],
    icon: "Browser",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "format",
        type: "select",
        label: "Output format",
        default: "jpg",
        options: [
          { value: "jpg", label: "JPG", hint: "A widely compatible image." },
          { value: "svg", label: "SVG", hint: "A scalable, self-contained graphic." },
        ],
      },
      {
        key: "viewportWidth",
        type: "number",
        label: "Viewport width",
        default: 1440,
        min: 320,
        max: 3840,
        step: 10,
        suffix: "px",
        hint: "Choose how wide the virtual browser should be.",
        presets: [
          { value: 375, label: "Phone" },
          { value: 768, label: "Tablet" },
          { value: 1440, label: "Desktop" },
          { value: 1920, label: "Wide" },
        ],
      },
    ],
  },
  {
    slug: "blur-face",
    name: "Blur Face",
    description: "Detect supported faces locally or blur a centered privacy region.",
    kind: "image",
    category: "security",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["privacy", "anonymize", "faces", "blur"],
    icon: "EyeSlash",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "strength",
        type: "range",
        label: "Blur strength",
        default: 24,
        min: 8,
        max: 48,
        step: 2,
        suffix: "px",
        minLabel: "Light blur",
        maxLabel: "Strong blur",
      },
    ],
  },
]);

export const categoryById = Object.freeze(
  Object.fromEntries(categories.map((category) => [category.id, category])),
);

export const pdfTools = Object.freeze(tools.filter((tool) => tool.kind === "pdf"));
export const imageTools = Object.freeze(
  tools.filter((tool) => tool.kind === "image"),
);

export function rankToolSearchResults(candidates, query, limit = 4) {
  const needle = String(query || "").trim().toLowerCase();
  if (!needle || !Array.isArray(candidates) || !Number.isInteger(limit) || limit < 1) return [];
  return candidates
    .map((tool, index) => {
      const name = tool.name.toLowerCase();
      const tags = tool.tags.map((tag) => tag.toLowerCase());
      const searchable = `${name} ${tool.description} ${tags.join(" ")} ${categoryById[tool.category]?.label || ""}`.toLowerCase();
      if (!searchable.includes(needle)) return null;
      const score = name === needle
        ? 0
        : name.startsWith(needle)
          ? 1
          : name.includes(needle)
            ? 2
            : tags.some((tag) => tag === needle || tag.startsWith(needle))
              ? 3
              : 4;
      return { tool, index, score };
    })
    .filter(Boolean)
    .sort((left, right) => left.score - right.score || left.index - right.index)
    .slice(0, limit)
    .map(({ tool }) => tool);
}

export default tools;
