// SPDX-FileCopyrightText: 2026 TeamBlackBox Private Limited
// SPDX-License-Identifier: Apache-2.0

const withPhosphorExports = (entries) =>
  Object.freeze(
    entries.map((entry) =>
      Object.freeze({ ...entry, icon: `${entry.icon}Icon` }),
    ),
  );

export const categories = withPhosphorExports([
  {
    id: "organize",
    label: "Organize",
    description: "Arrange, combine, separate, and capture document pages.",
    icon: "Stack",
    accent: "coral",
    order: 10,
  },
  {
    id: "optimize",
    label: "Optimize",
    description: "Reduce file size, restore files, and improve readability.",
    icon: "Gauge",
    accent: "emerald",
    order: 20,
  },
  {
    id: "convert",
    label: "Convert",
    description: "Move between document, image, web, and archive formats.",
    icon: "ArrowsLeftRight",
    accent: "amber",
    order: 30,
  },
  {
    id: "edit",
    label: "Edit",
    description: "Change pages, layouts, text, and image presentation.",
    icon: "PencilSimple",
    accent: "violet",
    order: 40,
  },
  {
    id: "create",
    label: "Create",
    description: "Build expressive images from photos, layouts, and captions.",
    icon: "Sparkle",
    accent: "pink",
    order: 50,
  },
  {
    id: "security",
    label: "Protect",
    description: "Secure, sign, compare, or conceal sensitive content.",
    icon: "ShieldCheck",
    accent: "teal",
    order: 60,
  },
  {
    id: "intelligence",
    label: "Smart",
    description: "Use on-device analysis to understand and transform content.",
    icon: "Brain",
    accent: "indigo",
    order: 70,
  },
]);

export const tools = withPhosphorExports([
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine PDFs and arrange them in the order you need.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: true,
    tags: ["combine", "join", "pages", "documents"],
    icon: "Files",
    featured: true,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Divide one PDF into the page groups you need.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf", ".zip"],
    batch: false,
    tags: ["separate", "extract", "ranges", "pages"],
    icon: "Scissors",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "mode",
        type: "choice",
        label: "Split method",
        default: "half",
        options: [
          { value: "half", label: "Split in half", hint: "Create two balanced PDFs." },
          { value: "every2", label: "Every 2 pages", hint: "Create consecutive two-page PDFs." },
          { value: "odd", label: "Odd pages", hint: "Group all odd pages in one PDF." },
          { value: "even", label: "Even pages", hint: "Group all even pages in one PDF." },
          { value: "custom", label: "Custom", hint: "Choose exactly where each PDF ends." },
        ],
      },
      {
        key: "customBreaks",
        type: "text",
        label: "Split after pages",
        default: "",
        hint: "Example: 3, 6 creates pages 1–3, 4–6, and 7 onward.",
      },
    ],
  },
  {
    slug: "remove-pdf-pages",
    name: "Remove Pages",
    description: "Delete selected pages while preserving the rest of the PDF.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["delete", "pages", "trim", "document"],
    icon: "FileMinus",
    featured: false,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "extract-pdf-pages",
    name: "Extract Pages",
    description: "Save selected PDF pages as one file or separate files.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf", ".zip"],
    batch: false,
    tags: ["copy", "select", "pages", "separate"],
    icon: "FileArrowUp",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "combine",
        type: "toggle",
        label: "Combine extracted pages",
        default: true,
      },
    ],
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    description: "Reorder, duplicate, or omit pages with an explicit page order.",
    kind: "pdf",
    category: "organize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["reorder", "sort", "duplicate", "pages"],
    icon: "Stack",
    featured: true,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Assemble uploaded camera images into an ordered PDF.",
    kind: "pdf",
    category: "organize",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".pdf"],
    batch: true,
    tags: ["camera", "capture", "document", "mobile"],
    icon: "Scan",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "pageSize",
        type: "select",
        label: "Page size",
        default: "auto",
        options: [
          { value: "auto", label: "Match image" },
          { value: "a4", label: "A4" },
          { value: "letter", label: "US Letter" },
        ],
      },
    ],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Shrink a PDF while balancing clarity and file size.",
    kind: "pdf",
    category: "optimize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["reduce", "shrink", "size", "quality"],
    icon: "FileZip",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "quality",
        type: "select",
        label: "Compression",
        default: "balanced",
        options: [
          { value: "gentle", label: "Gentle", badge: "Best clarity", hint: "Light reduction", description: "Keeps page images sharper and produces a larger result." },
          { value: "balanced", label: "Balanced", badge: "Recommended", hint: "Medium reduction", description: "A practical clarity and file-size trade-off for sharing." },
          { value: "strong", label: "Strong", badge: "Smallest target", hint: "Most reduction", description: "Uses lower image resolution; fine text may look softer." },
        ],
      },
    ],
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Rebuild a damaged PDF and recover readable content.",
    kind: "pdf",
    category: "optimize",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["fix", "recover", "corrupt", "restore"],
    icon: "Wrench",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "ocr-pdf",
    name: "OCR Reader",
    description: "Read and copy text from scanned English PDFs with on-device recognition.",
    kind: "pdf",
    category: "optimize",
    accepts: [".pdf"],
    output: ["text reader"],
    batch: false,
    tags: ["reader", "copy", "scan", "recognize", "text"],
    icon: "TextT",
    featured: true,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Turn JPG and PNG images into an ordered PDF.",
    kind: "pdf",
    category: "convert",
    accepts: [".jpg", ".jpeg", ".png"],
    output: [".pdf"],
    batch: true,
    tags: ["image", "photo", "convert", "combine"],
    icon: "FilePdf",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "pageSize",
        type: "select",
        label: "Page size",
        default: "fit",
        options: [
          { value: "fit", label: "Fit each image" },
          { value: "a4", label: "A4" },
          { value: "letter", label: "US Letter" },
        ],
      },
      {
        key: "margin",
        type: "select",
        label: "Margin",
        default: "small",
        options: [
          { value: "none", label: "None" },
          { value: "small", label: "Small" },
          { value: "large", label: "Large" },
        ],
      },
    ],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Extract readable DOCX text into a clean PDF without preserving the original layout.",
    kind: "pdf",
    category: "convert",
    accepts: [".docx"],
    output: [".pdf"],
    batch: false,
    tags: ["word", "docx", "text", "office"],
    icon: "FileDoc",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    description: "Extract PPTX slide text into a clean PDF without preserving slide layout.",
    kind: "pdf",
    category: "convert",
    accepts: [".pptx"],
    output: [".pdf"],
    batch: false,
    tags: ["powerpoint", "pptx", "text", "slides"],
    icon: "FilePpt",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Lay out spreadsheet cell text in a readable PDF without preserving workbook styling.",
    kind: "pdf",
    category: "convert",
    accepts: [".xls", ".xlsx"],
    output: [".pdf"],
    batch: false,
    tags: ["excel", "xls", "xlsx", "spreadsheet"],
    icon: "FileXls",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "orientation",
        type: "select",
        label: "Page orientation",
        default: "landscape",
        options: [
          { value: "portrait", label: "Portrait" },
          { value: "landscape", label: "Landscape" },
        ],
      },
    ],
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Extract readable text from local HTML into a clean, self-contained PDF.",
    kind: "pdf",
    category: "convert",
    accepts: [".html", ".htm"],
    output: [".pdf"],
    batch: false,
    tags: ["html", "webpage", "text", "document"],
    icon: "FileHtml",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "pageSize",
        type: "select",
        label: "Page size",
        default: "a4",
        options: [
          { value: "a4", label: "A4" },
          { value: "letter", label: "US Letter" },
        ],
      },
    ],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Render every PDF page as a JPG image.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".jpg", ".zip"],
    batch: false,
    tags: ["image", "photo", "pages", "extract"],
    icon: "FileJpg",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "quality",
        type: "range",
        label: "JPG quality",
        default: 88,
        min: 40,
        max: 100,
        step: 1,
        suffix: "%",
      },
    ],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Reconstruct selectable PDF text as an editable DOCX, one section per page.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".docx"],
    batch: false,
    tags: ["word", "docx", "editable", "office"],
    icon: "FileDoc",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Place selectable text from each PDF page onto a simple editable slide.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".pptx"],
    batch: false,
    tags: ["powerpoint", "pptx", "slides", "presentation"],
    icon: "FilePpt",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Place selectable text from each PDF page into a separate workbook sheet.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".xlsx"],
    batch: false,
    tags: ["excel", "xlsx", "pages", "spreadsheet"],
    icon: "FileXls",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-to-pdfa",
    name: "Archive PDF Rewrite",
    description: "Rewrite a PDF into an archive-friendly file; formal PDF/A conformance is not certified.",
    kind: "pdf",
    category: "convert",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["archive", "rewrite", "preserve", "normalize"],
    icon: "Archive",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate every page in a PDF by the selected angle.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["turn", "orientation", "pages", "landscape"],
    icon: "ArrowClockwise",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "angle",
        type: "select",
        label: "Rotation",
        default: 90,
        options: [
          { value: 90, label: "90° clockwise" },
          { value: 180, label: "180°" },
          { value: 270, label: "90° counter-clockwise" },
        ],
      },
    ],
  },
  {
    slug: "add-pdf-page-numbers",
    name: "Add Page Numbers",
    description: "Place sequential page numbers with a chosen position and starting number.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["number", "footer", "header", "pagination"],
    icon: "ListNumbers",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "position",
        type: "select",
        label: "Position",
        default: "bottom-center",
        options: [
          { value: "top-left", label: "Top left" },
          { value: "top-center", label: "Top center" },
          { value: "top-right", label: "Top right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
      {
        key: "startAt",
        type: "number",
        label: "Start at",
        default: 1,
        min: 1,
        step: 1,
      },
    ],
  },
  {
    slug: "watermark-pdf",
    name: "Add Watermark",
    description: "Stamp centered diagonal text across every PDF page.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["stamp", "text", "brand", "overlay"],
    icon: "Stamp",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "text",
        type: "text",
        label: "Watermark text",
        default: "CONFIDENTIAL",
      },
      {
        key: "opacity",
        type: "range",
        label: "Opacity",
        default: 25,
        min: 5,
        max: 100,
        step: 5,
        suffix: "%",
      },
    ],
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Trim the same percentage from every edge on every PDF page.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["trim", "margins", "area", "pages"],
    icon: "Crop",
    featured: false,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Place a text annotation at the same position on every PDF page.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["annotate", "text", "label", "pages"],
    icon: "PencilSimple",
    featured: true,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "add-image-to-pdf",
    name: "Add Image to PDF",
    description: "Place signatures or images anywhere on PDF pages with visual resize and rotation controls.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["signature", "image", "stamp", "overlay", "paste", "place"],
    icon: "ImageSquare",
    featured: true,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "pdf-forms",
    name: "PDF Forms",
    description: "Fill existing interactive PDF fields from local values.",
    kind: "pdf",
    category: "edit",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["form", "fields", "checkbox", "fillable"],
    icon: "Textbox",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "flatten",
        type: "toggle",
        label: "Flatten fields on export",
        default: false,
      },
    ],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove a PDF password when you are authorized to do so.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["password", "decrypt", "access", "open"],
    icon: "LockOpen",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "password",
        type: "password",
        label: "Current password",
        default: "",
        required: true,
      },
    ],
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Encrypt a PDF locally with an AES-256 password before sharing it.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["password", "encrypt", "secure", "privacy"],
    icon: "Lock",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "password",
        type: "password",
        label: "New password",
        default: "",
        required: true,
      },
    ],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Place a typed signature and optional date on the final PDF page.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["signature", "approve", "initial", "document"],
    icon: "Signature",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "includeDate",
        type: "toggle",
        label: "Include signing date",
        default: true,
      },
    ],
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently flatten a rectangular privacy region on every PDF page.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".pdf"],
    batch: false,
    tags: ["hide", "remove", "sensitive", "privacy"],
    icon: "EyeSlash",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "overlay",
        type: "select",
        label: "Redaction style",
        default: "black",
        options: [
          { value: "black", label: "Black box" },
          { value: "white", label: "White space" },
        ],
      },
    ],
  },
  {
    slug: "compare-pdf",
    name: "Compare PDF",
    description: "Compare selectable text from two PDFs and export an HTML change report.",
    kind: "pdf",
    category: "security",
    accepts: [".pdf"],
    output: [".html"],
    batch: false,
    tags: ["difference", "versions", "review", "changes"],
    icon: "Columns",
    featured: false,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "summarize-pdf",
    name: "Local Summarizer",
    description: "Create an extractive summary from selectable PDF text entirely on your device.",
    kind: "pdf",
    category: "intelligence",
    accepts: [".pdf"],
    output: [".txt"],
    batch: false,
    tags: ["summary", "extractive", "notes", "key points"],
    icon: "Sparkle",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "length",
        type: "select",
        label: "Summary length",
        default: "medium",
        options: [
          { value: "short", label: "Brief" },
          { value: "medium", label: "Standard" },
          { value: "long", label: "Detailed" },
        ],
      },
      {
        key: "format",
        type: "select",
        label: "Format",
        default: "bullets",
        options: [
          { value: "bullets", label: "Key points" },
          { value: "prose", label: "Paragraphs" },
        ],
      },
    ],
  },
  {
    slug: "translate-pdf",
    name: "Translate PDF",
    description: "Translate selectable English PDF text with an on-device model or a limited offline glossary.",
    kind: "pdf",
    category: "intelligence",
    accepts: [".pdf"],
    output: [".txt"],
    batch: false,
    tags: ["language", "translate", "localize", "offline"],
    icon: "Translate",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "targetLanguage",
        type: "select",
        label: "Translate to",
        default: "es",
        options: [
          { value: "hi", label: "Hindi" },
          { value: "es", label: "Spanish" },
          { value: "de", label: "German" },
          { value: "fr", label: "French" },
        ],
      },
    ],
  },
  {
    slug: "pdf-to-markdown",
    name: "PDF to Markdown",
    description: "Convert selectable PDF text into an editable Markdown draft.",
    kind: "pdf",
    category: "intelligence",
    accepts: [".pdf"],
    output: [".md"],
    batch: false,
    tags: ["markdown", "md", "text", "llm"],
    icon: "MarkdownLogo",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "pageBreaks",
        type: "toggle",
        label: "Mark page breaks",
        default: false,
      },
    ],
  },
  {
    slug: "compress-image",
    name: "Compress Image",
    description: "Re-encode JPG, PNG, or WebP images locally and remove metadata.",
    kind: "image",
    category: "optimize",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["reduce", "shrink", "quality", "optimize"],
    icon: "Images",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "quality",
        type: "range",
        label: "Quality",
        default: 82,
        min: 20,
        max: 100,
        step: 1,
        suffix: "%",
      },
    ],
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    description: "Resize image batches to a target width without distortion.",
    kind: "image",
    category: "edit",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["dimensions", "pixels", "percent", "scale"],
    icon: "Resize",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "width",
        type: "number",
        label: "Width",
        default: 1920,
        min: 1,
        step: 1,
        suffix: "px",
      },
    ],
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    description: "Crop photos freely or with a consistent aspect ratio.",
    kind: "image",
    category: "edit",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["trim", "aspect", "rectangle", "frame"],
    icon: "Crop",
    featured: true,
    maturity: "ready",
    settings: [
      {
        key: "aspectRatio",
        type: "select",
        label: "Aspect ratio",
        default: "free",
        options: [
          { value: "free", label: "Free" },
          { value: "1:1", label: "Square · 1:1" },
          { value: "4:3", label: "Standard · 4:3" },
          { value: "16:9", label: "Wide · 16:9" },
        ],
      },
    ],
  },
  {
    slug: "convert-to-jpg",
    name: "Convert to JPG",
    description: "Convert PNG, GIF, TIFF, SVG, and WebP images to JPG locally.",
    kind: "image",
    category: "convert",
    accepts: [
      ".png",
      ".gif",
      ".tif",
      ".tiff",
      ".svg",
      ".webp",
    ],
    output: [".jpg"],
    batch: true,
    tags: ["jpeg", "format", "webp"],
    icon: "FileJpg",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "quality",
        type: "range",
        label: "JPG quality",
        default: 90,
        min: 40,
        max: 100,
        step: 1,
        suffix: "%",
      },
      {
        key: "background",
        type: "color",
        label: "Transparency fill",
        default: "#ffffff",
      },
    ],
  },
  {
    slug: "convert-from-jpg",
    name: "Convert from JPG",
    description: "Turn JPG files into PNG images or an animated GIF.",
    kind: "image",
    category: "convert",
    accepts: [".jpg", ".jpeg"],
    output: [".png", ".gif"],
    batch: true,
    tags: ["png", "gif", "format", "animate"],
    icon: "ArrowsLeftRight",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "format",
        type: "select",
        label: "Output format",
        default: "png",
        options: [
          { value: "png", label: "PNG" },
          { value: "gif", label: "Animated GIF" },
        ],
      },
    ],
  },
  {
    slug: "photo-editor",
    name: "Photo Editor",
    description: "Adjust brightness, contrast, and saturation or add a text caption.",
    kind: "image",
    category: "create",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: false,
    tags: ["effects", "text", "brightness", "contrast"],
    icon: "Palette",
    featured: true,
    maturity: "beta",
    settings: [],
  },
  {
    slug: "upscale-image",
    name: "Upscale Image",
    description: "Enlarge an image with high-quality on-device resampling.",
    kind: "image",
    category: "optimize",
    accepts: [".jpg", ".jpeg", ".png"],
    output: [".jpg", ".png"],
    batch: true,
    tags: ["enlarge", "resolution", "resample", "scale"],
    icon: "ArrowsOut",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "scale",
        type: "select",
        label: "Scale",
        default: 2,
        options: [
          { value: 2, label: "2×" },
          { value: 4, label: "4×" },
        ],
      },
    ],
  },
  {
    slug: "remove-image-background",
    name: "Remove Background",
    description: "Remove simple, flat-color backgrounds with edge-aware local processing.",
    kind: "image",
    category: "optimize",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".png"],
    batch: true,
    tags: ["cutout", "transparent", "flat color", "background"],
    icon: "SelectionBackground",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "edgeQuality",
        type: "select",
        label: "Edge detail",
        default: "balanced",
        options: [
          { value: "fast", label: "Fast" },
          { value: "balanced", label: "Balanced" },
          { value: "fine", label: "Fine" },
        ],
      },
      {
        key: "background",
        type: "select",
        label: "Background",
        default: "transparent",
        options: [
          { value: "transparent", label: "Transparent" },
          { value: "white", label: "White" },
          { value: "black", label: "Black" },
        ],
      },
    ],
  },
  {
    slug: "watermark-image",
    name: "Watermark Image",
    description: "Apply a consistent text watermark across image batches.",
    kind: "image",
    category: "security",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["stamp", "brand", "copyright", "overlay"],
    icon: "Stamp",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "text",
        type: "text",
        label: "Watermark text",
        default: "© My work",
      },
      {
        key: "position",
        type: "select",
        label: "Position",
        default: "bottom-right",
        options: [
          { value: "center", label: "Center" },
          { value: "top-left", label: "Top left" },
          { value: "top-right", label: "Top right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
      {
        key: "opacity",
        type: "range",
        label: "Opacity",
        default: 45,
        min: 5,
        max: 100,
        step: 5,
        suffix: "%",
      },
    ],
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Overlay high-contrast top and bottom captions on an image.",
    kind: "image",
    category: "create",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: false,
    tags: ["caption", "text", "template", "social"],
    icon: "Smiley",
    featured: false,
    maturity: "ready",
    settings: [],
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    description: "Rotate image batches by a consistent angle.",
    kind: "image",
    category: "edit",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["turn", "orientation", "landscape", "portrait"],
    icon: "ArrowClockwise",
    featured: false,
    maturity: "ready",
    settings: [
      {
        key: "angle",
        type: "select",
        label: "Rotation",
        default: 90,
        options: [
          { value: 90, label: "90° clockwise" },
          { value: 180, label: "180°" },
          { value: 270, label: "90° counter-clockwise" },
        ],
      },
    ],
  },
  {
    slug: "html-to-image",
    name: "HTML to Image",
    description: "Render sanitized local HTML as a JPG or SVG without loading external assets.",
    kind: "image",
    category: "convert",
    accepts: [".html", ".htm"],
    output: [".jpg", ".svg"],
    batch: false,
    tags: ["html", "webpage", "screenshot", "svg"],
    icon: "Browser",
    featured: false,
    maturity: "beta",
    settings: [
      {
        key: "format",
        type: "select",
        label: "Output format",
        default: "jpg",
        options: [
          { value: "jpg", label: "JPG" },
          { value: "svg", label: "SVG" },
        ],
      },
      {
        key: "viewportWidth",
        type: "number",
        label: "Viewport width",
        default: 1440,
        min: 320,
        max: 3840,
        step: 1,
        suffix: "px",
      },
    ],
  },
  {
    slug: "blur-face",
    name: "Blur Face",
    description: "Detect supported faces locally or blur a centered privacy region.",
    kind: "image",
    category: "security",
    accepts: [".jpg", ".jpeg", ".png", ".webp"],
    output: [".jpg", ".png", ".webp"],
    batch: true,
    tags: ["privacy", "anonymize", "faces", "blur"],
    icon: "EyeSlash",
    featured: true,
    maturity: "beta",
    settings: [
      {
        key: "strength",
        type: "range",
        label: "Blur strength",
        default: 24,
        min: 8,
        max: 48,
        step: 2,
        suffix: "px",
      },
    ],
  },
]);

export const categoryById = Object.freeze(
  Object.fromEntries(categories.map((category) => [category.id, category])),
);

export const pdfTools = Object.freeze(tools.filter((tool) => tool.kind === "pdf"));
export const imageTools = Object.freeze(
  tools.filter((tool) => tool.kind === "image"),
);

export default tools;
